spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    include: oauth2, mysql
logging:
  level:
    org.springframework.security: DEBUG
